# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: thearmchair.in
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  secret_key_base: 3ce9d9234cb47dbddf37046578fbe5fa9870ead90b0107b1c214f76acec66f0e3ac1ae763ea8f6a43a7ec11d6dc4b090e554da00ff07356bc1d2fcfee99a0f99

test:
  secret_key_base: 08f7a454f86f58058a9e46d5cd88ed55f9a74f88d264cca2d4cc6f2047bd1ad16ca9e29126bb2b6ce2df0cff9a3759a1f985ecbd5ec27e18788c7e3253469e9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
